name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  ci:
    name: ✅ CI (Lint, Build)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Check linting
        run: npm run lint

      - name: Build the project
        run: npm run build
